# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- prod

pool:
  name: Default
  demands:
    - agent.name -equals selfhosted_agentpool

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo "Running on agent: $(Agent.Name)"
      echo "Current directory: $(Build.SourcesDirectory)"
      echo "Hello from Linux shell!"
      uname -a
      df -h
      whoami
- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1(a7227ddf-a84b-488c-9757-267492f738eb)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false