# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- prod

pool:
  name: AGENTPOOL-Azure
  demands:
    - agent.name -equals AgentPipeline

steps:
- task: CmdLine@2
  inputs:
    script: |
      source /etc/profile.d/maven.sh
      echo "Running on agent: $(Agent.Name)"
      echo "Current directory: $(Build.SourcesDirectory)"
      echo "Hello from Linux shell!"
      uname -a
      df -h
      whoami
      mvn --version

- task: CmdLine@2
  inputs:
    script: |
      source /etc/profile.d/maven.sh
      echo "Running Maven build"
      mvn clean package

- task: CmdLine@2
  inputs:
    script: |
      source /etc/profile.d/maven.sh
      echo "Running Maven deploy"
      mvn deploy
